# Generated by Django 4.1.4 on 2023-01-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_subscription', '0002_remove_subscriptionduration_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
