# Generated by Django 4.1.4 on 2023-01-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_subscription', '0004_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribermodel',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
